apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: markjava
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: markjava
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/markjava
      ref:
        branch: main